export interface GalleryItem {
  id: string;
  title: string;
  author: string;
  date: string;
  imagePath: string; // Thumbnail image path
  fullImagePaths: string[]; // All images for the gallery item
}

export const galleryData: GalleryItem[] = [
  {
    id: "2024-christmas",
    title: "2024 성탄발표회",
    author: "이진우",
    date: "2024.12.29",
    imagePath: "/images/uploads/갤러리/2024성탄/2024성탄1.jpeg",
    fullImagePaths: [
      "/images/uploads/갤러리/2024성탄/2024성탄1.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄2.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄3.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄4.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄5.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄6.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄7.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄8.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄9.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄10.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄11.jpeg",
      "/images/uploads/갤러리/2024성탄/2024성탄12.jpeg",
    ],
  },
  {
    id: "40th-anniversary",
    title: "교회창립40주년 기념음악회",
    author: "이진우",
    date: "2024.10.20",
    imagePath: "/images/uploads/갤러리/40주년/40주년 (1).jpg",
    fullImagePaths: [
      "/images/uploads/갤러리/40주년/40주년 (1).jpg",
      "/images/uploads/갤러리/40주년/40주년 (2).jpg",
      "/images/uploads/갤러리/40주년/40주년 (3).jpg",
      "/images/uploads/갤러리/40주년/40주년 (4).jpg",
      "/images/uploads/갤러리/40주년/40주년 (5).jpg",
      "/images/uploads/갤러리/40주년/40주년 (6).jpg",
      "/images/uploads/갤러리/40주년/40주년 (7).jpg",
      "/images/uploads/갤러리/40주년/40주년 (8).jpg",
      "/images/uploads/갤러리/40주년/40주년 (9).jpg",
      "/images/uploads/갤러리/40주년/40주년 (10).jpg",
      "/images/uploads/갤러리/40주년/40주년 (11).jpg",
    ],
  },
  {
    id: "2nd-world-mission",
    title: "제2회 세계선교대회",
    author: "이진우",
    date: "2024.09.22",
    imagePath: "/images/uploads/갤러리/2회세계선교/2세계선교 (1).jpg",
    fullImagePaths: [
      "/images/uploads/갤러리/2회세계선교/2세계선교 (1).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (2).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (3).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (4).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (5).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (6).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (7).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (8).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (9).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (10).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (11).jpg",
      "/images/uploads/갤러리/2회세계선교/2세계선교 (12).jpg",
    ],
  },
  {
    id: "40th-anniversary-worship",
    title: "40주년 기념예배",
    author: "이진우",
    date: "2024.05.26",
    imagePath: "/images/uploads/갤러리/40예배/40예배 (1).jpg",
    fullImagePaths: [
      "/images/uploads/갤러리/40예배/40예배 (1).jpg",
      "/images/uploads/갤러리/40예배/40예배 (2).jpg",
      "/images/uploads/갤러리/40예배/40예배 (3).jpg",
      "/images/uploads/갤러리/40예배/40예배 (4).jpg",
      "/images/uploads/갤러리/40예배/40예배 (5).jpg",
      "/images/uploads/갤러리/40예배/40예배 (6).jpg",
      "/images/uploads/갤러리/40예배/40예배 (7).jpg",
      "/images/uploads/갤러리/40예배/40예배 (8).jpg",
      "/images/uploads/갤러리/40예배/40예배 (9).jpg",
      "/images/uploads/갤러리/40예배/40예배 (10).jpg",
      "/images/uploads/갤러리/40예배/40예배 (11).jpg",
      "/images/uploads/갤러리/40예배/40예배 (12).jpg",
      "/images/uploads/갤러리/40예배/40예배 (13).jpg",
      "/images/uploads/갤러리/40예배/40예배 (14).jpg",
      "/images/uploads/갤러리/40예배/40예배 (15).jpg",
    ],
  },
  {
    id: "charity-bazaar",
    title: "사랑의 바자회",
    author: "이진우",
    date: "2024.05.26",
    imagePath: "/images/uploads/갤러리/25바자회/25 바자회 (1).jpg",
    fullImagePaths: [
      "/images/uploads/갤러리/25바자회/25 바자회 (1).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (2).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (3).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (4).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (5).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (6).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (7).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (8).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (9).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (10).jpg",
      "/images/uploads/갤러리/25바자회/25 바자회 (11).jpg",
    ],
  },
  {
    id: "taiwan-mission-visit",
    title: "대만 운가남 선교연합회 방문",
    author: "이진우",
    date: "2023.10.01",
    imagePath: "/images/uploads/갤러리/대만선교연합회/대만선교 (1).jpg",
    fullImagePaths: [
      "/images/uploads/갤러리/대만선교연합회/대만선교 (1).jpg",
      "/images/uploads/갤러리/대만선교연합회/대만선교 (2).jpg",
      "/images/uploads/갤러리/대만선교연합회/대만선교 (3).jpg",
      "/images/uploads/갤러리/대만선교연합회/대만선교 (4).jpg",
      "/images/uploads/갤러리/대만선교연합회/대만선교 (5).jpg",
      "/images/uploads/갤러리/대만선교연합회/대만선교 (6).jpg",
      "/images/uploads/갤러리/대만선교연합회/대만선교 (7).jpg",
    ],
  },
];
